#!/usr/bin/env node
/**
 * Bundles src/content.js (and the src/lib/*.js modules it imports) into
 * src/content.bundle.js — a single-file IIFE that the Chrome content-script
 * loader actually injects.
 *
 * Why bundle:
 *   MV3 content scripts loaded via chrome.scripting.registerContentScripts
 *   can't use native ES module `import` — each entry in the `js: [...]` array
 *   is injected as a regular script in shared scope. Bundling lets us split
 *   the source into small testable modules (src/lib/*.js) while still shipping
 *   a single artifact, which keeps the manifest registration and review story
 *   simple.
 *
 * Why a gitignored bundle:
 *   src/content.bundle.js is regenerated by every contributor via
 *   `npm run build`. Committing the build artifact would be diff noise.
 *   build-store-zip.sh runs the build as gate 1/N; CI builds via npm ci.
 */
import esbuild from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(__dirname, "src");

const watch = process.argv.includes("--watch");

const config = {
  entryPoints: [path.join(SRC, "content.js")],
  bundle: true,
  format: "iife",
  target: ["chrome114"],
  platform: "browser",
  outfile: path.join(SRC, "content.bundle.js"),
  legalComments: "none",
  // Plain JS source, so no source maps in the shipped extension — keeps the
  // CWS review surface tight. Flip to "inline" locally if you ever need them.
  sourcemap: false,
  // Match the existing inline-IIFE style: no extra wrapper, no minification,
  // readable diff. The bundler still inlines the `import` graph.
  minify: false,
  banner: {
    js: "// THIS FILE IS GENERATED BY esbuild.config.mjs — do not edit by hand.\n// Source: src/content.js + src/lib/*.js",
  },
};

if (watch) {
  const ctx = await esbuild.context(config);
  await ctx.watch();
  console.log("[esbuild] watching src/content.js + src/lib/*.js → src/content.bundle.js");
} else {
  await esbuild.build(config);
  console.log("[esbuild] built src/content.bundle.js");
}
